### PR TITLE
document input file options: .txt, .xml, and .dic/.aff.

### PR DESCRIPTION
**Pull request by jstnlth**
The input file is all-important in this process. Add some wording
to at least suggest what options are available without requiring
people to browse through the code to discover it.

### CODE REVIEW

**Comment by mhosken** [comment]
All looks good. Not sure why you removed the moving makeoxt.exe to current directory. @DavidLRowe are you happy with these changes?

**Comment by jstnlth** [comment]
the windowsInstall.md "- Copy makeoxt.exe to working folder." is not a removal - that is just the way that the text looks in the document - part the of "surrounding text" of the change.

**Review by DavidLRowe — APPROVED** [review]
Looks good to me

**Comment by DavidLRowe** [comment]
(The - in front of the line about moving makeoxt.ext to current directory is part of the markdown for a bulleted list item rather than an indication that the line was removed.)

**Pull request merged**
